stages:
  - test

test:
  image: ${CI_REGISTRY}/ict/images/alpine/ci:latest
  stage: test
  before_script:
    - apk add --no-cache nodejs
    - apk add --no-cache npm
  script:
    - npm install
    - npm test
